### ISSUE TITLE
Import statements added by plugins are not transformed properly

### ISSUE THREAD

**Issue by douglasviehbeck** [nonara/ts-patch#112] opened 2023-07-16 00:02 UTC
I'm trying to create a plugin that add `import` statements to files being built. When there are no other `import` statements in the original TS file, `import` statements added by plugins are not transformed properly:

Plugin code:
```ts
import type * as ts from 'typescript';

export default function () {
  return (ctx: ts.TransformationContext) => {
    const { factory } = ctx;

    return (sourceFile: ts.SourceFile) => {
      return factory.updateSourceFile(sourceFile, [
        factory.createImportDeclaration(
          undefined,
          factory.createImportClause(
            false,
            undefined,
            factory.createNamedImports([
              factory.createImportSpecifier(false, undefined, factory.createIdentifier('exampleImport')),
            ]),
          ),
          factory.createStringLiteral('example-module'),
        ),
        ...sourceFile.statements,
      ]);
    };
  };
}
```

Original index.ts file:
```ts
console.log('Hello');
```

Generated index.js file:
```js
"use strict";
import { exampleImport } from "example-module";
console.log('Hello');
```

This causes errors in `CommonJS` modules, as they don't support `import` statements.

But, if there are any imports in the original TS files, the `import` statements added by the plugin are transformed just as the file `import` statements:

Original index.ts file with imports:
```ts
import ts from 'typescript';

console.log('Hello', ts.version);
```

Generated index,js file with imports:
```js
"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const example_module_1 = require("example-module");
const typescript_1 = __importDefault(require("typescript"));
console.log('Hello', typescript_1.default.version);
```

As you can see, `example-module` is now being required.

As an additional problem that I'm facing, any reference to an `import` statement that was added does not reference the new transformed `import` statements:

Plugin code:
```ts
import type * as ts from 'typescript';

export default function () {
  return (ctx: ts.TransformationContext) => {
    const { factory } = ctx;

    return (sourceFile: ts.SourceFile) => {
      const importStatement = factory.createImportDeclaration(
        undefined,
        factory.createImportClause(
          false,
          undefined,
          factory.createNamedImports([
            factory.createImportSpecifier(false, undefined, factory.createIdentifier('exampleImport')),
          ]),
        ),
        factory.createStringLiteral('example-module'),
      );
      const callStatement = factory.createExpressionStatement(
        factory.createCallExpression(factory.createIdentifier('exampleImport'), undefined, undefined),
      );

      return factory.updateSourceFile(sourceFile, [importStatement, callStatement, ...sourceFile.statements]);
    };
  };
}
```

Original index.ts file:
```ts
import ts from 'typescript';

console.log('Hello', ts.version);
```

Generated index.js file:
```js
"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const example_module_1 = require("example-module");
exampleImport();
const typescript_1 = __importDefault(require("typescript"));
console.log('Hello', typescript_1.default.version);
```

`tsconfig.json` file:
```json
{
  "compilerOptions": {
    "target": "ES2020",
    "module": "commonjs",
    "rootDir": "./src",
    "outDir": "./dist",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,

    "strict": true,
    "skipLibCheck": true,
    "plugins": [
      {
        "transform": "./plugin.ts"
      }
    ],
    "types": ["node"]
  },
  "include": ["./src/**/*"],
  "exclude": ["node_modules"]
}
```

**Comment by nonara** [comment] 2023-07-16 01:07
Hello. Sorry to hear you're having issues. 

From the sound of it, I dont think that these are issues with this library. 

The first issue is unusual, though I imagine that this is because a file which has no imports / exports is marked as such somehow during the type walking process. Which also brings us to the second issue.

The second issue is definitely due to the fact that the typescript compiler does not walk types again after transformation, so the typechecker doesn't know the identifier in your call expression is linked to something. 

Basically, before transforming, the type checker walks through everything, determines and resolves types, and makes symbols for things. When you transform and add or modify things, it doesn't do this process again, so these updates are unknown within the typechecker.

To get around these issues, you can use a Program transformer so you can recreate the program to re-walk the types after a transform. There's an example of that linked in the docs. But, this breaks source maps. It also is generally overkill for most situations.

As for yours...

I don't think you'd need to do that. It sounds like you'd be better off simply using an `after` transformer.

This would allow you take the compiled cjs code and modify it directly. That way you can insert your import as a `const { ... } = require(...);` and you can trust it will be safe to use a call expression with the same identifier. That'd be my advice!

If you need to go the other route, you might be able to get some help in the compiler api discord. Someone there might be able to tell you why your sourcefile without import / export is being handled that way and how to ensure it gets treated properly during transform. Maybe it's as simple as a flag you can set.

What you're describing _almost_ strikes me as something worth at least raising with the compiler team, though I'm always hesitant to do that. That edge case is at least what I would consider to be unexpected behaviour for a transformer on a `.ts` file with a cjs module config. That in mind, it might be worth creating an issue on the TS repo. Most likely, you'll get a good reason as to why it is that way and a way to work around it.

If you do file an issue, if you'd kindly let me know here, I'd be interested in following.

Best of luck!

**Closed** 2023-07-16 01:07 UTC
